### ISSUE TITLE
ADH example

### ISSUE THREAD

**Issue by Dee1808** [zhangxiang0822/ShiftShareSEStata#2]
Hi, 
For the ADH example, do you have the data cleaning and variable construction do file to understand how you reached the variables used in "ADHapplication.do"
Any help would be appreciated. 
Thank you

**Comment by xiangzhang-econ** [comment]
Sure, I uploaded the code as `preclean.do`. This code should be helpful in explaining how to merge employment share data (employment share data is used to construct the shift-share IV) to the raw dataset (CZ-level independent and dependent variables).

The employment share data, as well as the raw ADH dataset, should be directly available from the ADH paper. Sorry that I cannot include it here for copyright concerns. Thanks!
