### ISSUE TITLE
-ivreg_ss- with nonlinear 2nd stage, or with control function approach?

### ISSUE THREAD

**Issue by meierpeter** [zhangxiang0822/ShiftShareSEStata#3]
Hi Xiang,

thanks so much for providing the -ivreg_ss- code in Stata! That will be very useful for many researchers who can use and cite it. I have 2 possible applications which I have not yet figured out how to implement with the existing ado file:

(1) Estimate an IV model where the 2nd stage regression is non-linear, e.g. a Probit or Logit.

(2) Estimate the 2nd stage as "control function approach" in which the 2nd stage would regress the outcome of interest on the endogenous regressor rather than on its prediction, but would control for the first stage residuals. This should allow me to estimate in the 2nd stage the marginal effects of X exceeding several different thresholds.

Unless you already see econometric reasons speaking against this, can you see a way to implement this with the existing Ado, or would you find it feasible to add corresponding options to the ado code in the near future?

Thanks so much!

**Comment by xiangzhang-econ** [comment]
Hi,

Sorry that I'm not sure if the AKM method is suitable for extending to a Probit/Logit second-stage, or if it's suitable for a "control function approach". Maybe you could directly contact the authors of the paper for guidance.

Thanks!
