### ISSUE TITLE
Stata error "Type mismatch"

### ISSUE THREAD

**Issue by MathildeLeMoigne** [zhangxiang0822/ShiftShareSEStata#5]
Hi Zhang,

First of all, thank you so much for your work, it is amazing to be able to use the routine so quickly. 

I am writing you because I am confused as to the error I keep receiving when trying to use both reg_ss and ivreg_ss. I do a shiftshare analysis absolutely equivalent to the one in ADH with the same instrument, but with German data. I've transformed all the missing values of my datasets in zeros, and got rid of all the collinear vectors of the emp_share matrix manually. But when I run the following, I get the error "Type mismatch" :

reg_ss Dqwskm_v_5_dem, shiftshare_var(Dqwskm_v_5_inst_dem) control_varlist(CLtradec_w_share CLroutinec_w_share CLfc_w_share CLforeignc_w_share Ccollective_w Cbetrrat_w) share_varlist(wwm_*) alpha(0.05) akmtype(1)

I have no string variable in my datasets. I tried adding a weight_var of value 1 for each region, replace the control_varlist by a local list as you do in your example, renamed all my shares emp_share* from 1 to its max, rather than keep the original name of wwm_*. Yet I keep receiving that error. Comparing with the example dataset, some of my endogenous variables and instrument variables have zeros because they have no manufacturing employment, the same is true for some observations in my dependent variables, but no missing value since all has been cleaned up. 

Edit: I also tested the command exactly your wrote it in the example, with the replication dataset you made available. I obtain the same error, could this be dependent of some stata version? 

Thank you very much for any indication of what I could have missed.

With best regards

**Comment by paulpelzl** [comment]
I have exactly the same issue! Did you find a solution for this in the meanwhile?

**Comment by MathildeLeMoigne** [comment]
I did. So there are a few basics that Zhang explains in the description:
- no missing values
- no string variables
- I turned my fixed effects into an actual set of dummies rather than using the i. handle from Stata

The key issue that can arise after that (that is explained in the original paper) is that if some of your weights vectors are collinear, and that will block the code. So You have to get rid of these.  So if you have weights by region x year of observation, some of them will be a linear combination of the other ones, and these ones need to be dropped. They do it in matlab, I did it manually in Stata, but either way that's going to be crucial.
